name: Backup Repo to Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'   # UTC 2 点（北京时间 10 点）

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pack source
        run: |
          TS=$(date +"%Y%m%d-%H%M%S")
          echo "TS=$TS" >> $GITHUB_ENV

          mkdir -p /tmp/backup
          tar -czf /tmp/backup/src-$TS.tar.gz \
          --exclude=.git \
          .

          sha256sum /tmp/backup/src-$TS.tar.gz > /tmp/backup/src-$TS.tar.gz.sha256

          mv /tmp/backup/* .
